src/bffbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
    path('api1/', include('api.router')),
    path('api2/', include('api1.router')),
    path('market/', include('marketplace.urls', namespace='market')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/marketplace/urls.py
from django.urls import path
from .views import ItemListView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView, MarketCommunicationCreateView

app_name = 'market'

urlpatterns = [
    path('', ItemListView.as_view(), name='item-list'),
    path('<int:pk>/', ItemDetailView.as_view(), name='item-detail'),
    path('create/', ItemCreateView.as_view(), name='item-create'),
    path('<int:pk>/update/', ItemUpdateView.as_view(), name='item-update'),
    path('<int:pk>/delete/', ItemDeleteView.as_view(), name='item-delete'),
    path('<int:pk>/communication/', MarketCommunicationCreateView.as_view(), name='communication-create'),
]

src/posts/urls.py
from django.urls import path, include
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView
from profiles.views import ProfileDetailView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),

]

src/profiles/urls.py
from django.urls import path, include
from .views import (
                    my_profile_view,
                    invites_received_view, 
                    profiles_list_view, 
                    invite_profiles_list_view,
                    ProfileDetailView,
                    ProfileListView,
                    send_invatation,
                    remove_from_friends,
                    accept_invatation,
                    reject_invatation,  
)


app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/acctept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
]

src/templates/main/footer.html
<footer class="ui inverted vertical segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">Enlaces importantes</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Acerca de nosotros</a>
            <a href="#" class="item">Contacto</a>
            <a href="#" class="item">Preguntas frecuentes</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Redes sociales</h4>
          <div class="ui inverted link list">
            <a href="#" class="item"><i class="facebook icon"></i> Quienes somos</a>
            <a href="#" class="item"><i class="twitter icon"></i> Twitter</a>
            <a href="#" class="item"><i class="linkedin icon"></i> LinkedIn</a>
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">Acerca de este sitio web</h4>
          <p>Este es un sitio web creado para mostrar un ejemplo de cómo utilizar Semantic UI en HTML. </p>
        </div>
      </div>
    </div>
  </footer>
  

src/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title%}

{% block content %}


<div class="ui grid">
    <div class="sixteen wide column">
        <div class="ui segment">
      <!-- Contenido para la primera columna -->
      <h1> Hello {{user}} this is my Django Blog for Lumetrio Project, below, are some post create already for the users</h1>
        </div>
        <div class="">
            {% for obj in qs %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                    <div class="row">
                        {% if request.user == obj.author.user %}.
                            <a href=" {% url 'posts:post-update' obj.pk %} "><button class="ui button bwhite-lg ">Update</button></a>
                            <a href=" {% url 'posts:post-delete' obj.pk %} "><button class="ui button bwhite-lg ">Delete</button></a>
                        {% endif %}
                    </div>
                </div>
                    
                </div>
                <img class="ui avatar image" src={{obj.author.avatar.url}}> 
                {{ obj.author.user }} - {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image img-post">
                {% if obj.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <p> {{ obj.content }} </p>
                <div class="right floated">
                    <form action="{% url 'posts:like-post-view' %}" method="POST" class='like-form' id='{{obj.id}}'>
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        
                            <button type="submit" class="ui button like-btn{{obj.id}}">
                                {% if profile not in obj.liked.all %}
                                    Like
                                {% else %}
                                    Unlike
                                {% endif %}
                            </button>
                            <div class="ui grid">
                                <div class="column">
                                    <div class="like-count{{obj.id}}"> {{obj.num_likes}} </div>
                                </div>
                                <div class="column">
                                    likes
                                </div>
                            </div>
                    </form>
                </div>
                <i class="comment icon"></i>
                <span> {{ obj.num_comments }} comments</span>
            </div>
            <div class="extra content">
                <div class="mb-5">
                  
                </div>
                <button class="cmt_btn ui button mb-5">show / hide comments</button>
                <div class="comment-box">
                {% if obj.comment_set.all %}
                    {% for c in obj.comment_set.all %}
                    
                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{c.user.avatar.url}}>
                            <span>{{ c.user }}</span>
                            <div class='mt-5'>{{ c.body }}</div>
                        </div>
                    
                    {% endfor %}
                {% endif %}
                </div>
  
                <form action="" method=""class='ui fluid form'>
                    {% csrf_token %}
                    <input type="hidden" >
                    {{ c_form }}
                    <a href="{% url 'account_login' %}" class="ui primary button mt-5 w-full"> Send</a>
                </form>
            </div>
        </div>


        {% endfor %}
        </div>
    </div>
    
  </div>
  

{% endblock content%}

{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });
        });
    </script>
{% endblock scripts %}

src/templates/main/navbar.html
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'home-view' as path_to_home %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}
{% load static %}
<div class="ui inverted menu nav mb-7 sm">
    <div class="ui container">
      {% if not request.user.is_authenticated %}
      <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item borde">
          <img src="{% static 'BFF.Book.png' %}"> &nbsp; &nbsp; BFF BOOK 
      </a>
      {% else %}
      <a class="{% if request.path == path_to_home %}active{% endif %} item borde">
        <img src="{% static 'BFF.Book.png' %}"> &nbsp; &nbsp; BFF BOOK 
    </a>
      {% endif %}
      {% if not request.user.is_authenticated %}
      <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item border">
        <i class="copy outline icon"></i>  Board
      </a>
      {% endif %}
      {% if request.user.is_authenticated %}
      <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item border">
        <i class="copy outline icon"></i>  Board
      </a>
      {% comment %} <div class="item">
        <div class="ui floating dropdown icon button teal"> Friends
            <i class="dropdown icon"></i>
            <div class="menu">
                <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                    All Profiles
                </a>
                <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                    Send Invites
                </a>
                <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                    Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                </a>
            </div>
         </div>
    </div> {% endcomment %}
      <a href="{% url 'market:item-list' %}" class="{% if request.path == path_to_market %}active{% endif %} item border"><i class="money bill alternate outline icon"></i> Marketplace</a>
      {% endif %}
      <div class="right menu">
          {% if request.user.is_authenticated %}
          <nav class="item linea">               
                  <ul class="clasmenu">
                      <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item border">
                        <i class="address book outline icon"></i>  All Profiles
                      </a>
                      <a href="{{path_to_invites}}" class="{% if request.user == path_to_invites %}active{% endif %} item border">
                        <i class="clipboard check icon"></i>  Send Invites
                      </a>
                      <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item border">
                        <i class="book icon"></i> Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                      </a>
                    </ul>
            </nav>
            
              <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item border">
                   <img src={{picture.url}} class='ui avatar image'>&nbsp;
                {{ request.user }}
              </a>
  
              <a href="{% url 'account_logout' %}" class="ui item border">
                  Logout
              </a>
          {% else %}
          <a href="{% url 'account_login' %}" class="ui item border">
                  Login
              </a>
            <a href="{% url 'account_signup' %}" class="ui item border">
                Register
            </a>
          {% endif %}
      </div>
    </div>
  </div>


  {% comment %} <div class="item">
                <form action="" method="GET">
                  <div class="ui action left icon input">
                  <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                  <i class="search icon"></i>
                  <button type='submit' class="ui button">Search</button>
                  </div>
              </form>
              </div> {% endcomment %}